name: Build and Push to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Cloner le dépôt
        uses: actions/checkout@v3

      - name: Installer les dépendances
        run: |
          npm install  # Adapter selon la stack

      - name: Exécuter les tests
        run: |
          npm test  # Adapter selon la stack

      - name: Analyse SonarQube
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          sonar-scanner -Dsonar.projectKey=mon-projet -Dsonar.organization=mon-org -Dsonar.host.url=https://sonarcloud.io

      - name: Contrôle de sécurité OWASP
        run: |
          npx owasp-dependency-check --project "mon-projet"

      - name: Construire l’image Docker
        run: |
          docker build -t mon-repo/mon-image:latest .

      - name: Se connecter à Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Pousser l’image Docker
        run: |
          docker push mon-repo/mon-image:latest
